version: '1.0'

services:
  nest-app:
    image: mlaku-mulu-service:latest
    ports:
      - "3002:3002"
    environment:
      PORT: ${PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALT_OR_ROUNDS: ${SALT_OR_ROUNDS}